// Mirrors the type discriminators of `Core_HarmonizeEventPayload` in the
// custody SDK. The SDK types `supportedEventTypes` as a loose-autocomplete
// union, so any string is accepted at runtime — these are the known values.
export const KNOWN_EVENT_TYPES = [
  "AccountCreated",
  "AccountUpdated",
  "AddressCreated",
  "BackupCreated",
  "BackupUpdated",
  "BalancesUpdated",
  "ComplianceConfigurationUpdated",
  "DomainCreated",
  "DomainUpdated",
  "EndpointCreated",
  "EndpointUpdated",
  "GenesisSucceeded",
  "IntentClosed",
  "IntentCreated",
  "IntentExecuted",
  "IntentUpdated",
  "LedgerCreated",
  "LedgerUpdated",
  "ManifestCreated",
  "ManifestUpdated",
  "PolicyCreated",
  "PolicyUpdated",
  "QuarantineApplied",
  "QuarantineSkipped",
  "SystemPropertySet",
  "TickerCreated",
  "TickerUpdated",
  "TransactionCreated",
  "TransactionDetected",
  "TransactionUpdated",
  "TransferUpdated",
  "TrustedPublicKeyAdded",
  "TrustedPublicKeyUpdated",
  "UserCreated",
  "UserUpdated",
  "VaultCreated",
  "VaultKeyMaterialRewrapCompleted",
  "VaultKeyMaterialRewrapFailed",
  "VaultUpdated",
] as const;

export type KnownEventType = (typeof KNOWN_EVENT_TYPES)[number];
